# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MeshbrowMcp < Formula
  desc "MCP server for Meshbrow — gives AI agents stealth browser capabilities"
  homepage "https://meshbrow.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meshbrow-dev/meshbrow-mcp/releases/download/v0.1.0/meshbrow-mcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "c11388fd0ce14decdc167a2072b55ded3d9e81493b5ee626b6c9b24a05ef22e6"

      define_method(:install) do
        bin.install "meshbrow-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meshbrow-dev/meshbrow-mcp/releases/download/v0.1.0/meshbrow-mcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "151fa69c1ab11deaf474cbe1ac38b4e89acecd980a05c82b4a9814fe6ad293a6"

      define_method(:install) do
        bin.install "meshbrow-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-mcp/releases/download/v0.1.0/meshbrow-mcp_0.1.0_linux_amd64.tar.gz"
      sha256 "55ac371cba710560e957dcbc72a9d21a3111eba8ea73e3af7d3d8a9ea46276e9"
      define_method(:install) do
        bin.install "meshbrow-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-mcp/releases/download/v0.1.0/meshbrow-mcp_0.1.0_linux_arm64.tar.gz"
      sha256 "4a85b85e27fcb8b6353ea5579fe46e22e671d06442882d1abbb534cc2a7baa6e"
      define_method(:install) do
        bin.install "meshbrow-mcp"
      end
    end
  end
end
