# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MeshbrowAgent < Formula
  desc "Browser session agent for the Meshbrow managed fleet"
  homepage "https://meshbrow.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meshbrow-dev/meshbrow-agent/releases/download/v0.1.0/meshbrow-agent_0.1.0_darwin_amd64.tar.gz"
      sha256 "2ac10497a9676bc4fda96063b8558f486ba22921ad3e2fb54dde5889af3773aa"

      define_method(:install) do
        bin.install "meshbrow-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meshbrow-dev/meshbrow-agent/releases/download/v0.1.0/meshbrow-agent_0.1.0_darwin_arm64.tar.gz"
      sha256 "2fe2a62e56eb42b52e2bd99892bfa281f175a9b8b4ceb8a3b9d3f796a2dbe02d"

      define_method(:install) do
        bin.install "meshbrow-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-agent/releases/download/v0.1.0/meshbrow-agent_0.1.0_linux_amd64.tar.gz"
      sha256 "c4318876c0c4c316f57022b59aded8de0777e712d463a2be6bd01487ec52ab5f"
      define_method(:install) do
        bin.install "meshbrow-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-agent/releases/download/v0.1.0/meshbrow-agent_0.1.0_linux_arm64.tar.gz"
      sha256 "173aeabac80434bfde373abb92c9b0e33fc04ee0171abec35967fca8472f4670"
      define_method(:install) do
        bin.install "meshbrow-agent"
      end
    end
  end
end
