# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meshbrow < Formula
  desc "CLI for the Meshbrow Managed Browser Fleet"
  homepage "https://meshbrow.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_darwin_amd64.tar.gz"
      sha256 "5a7ec8f1f5715980f7f52955a2ba0824aac8e86221de3622d87ccec57939af4e"

      define_method(:install) do
        bin.install "meshbrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_darwin_arm64.tar.gz"
      sha256 "808d0116445909f0da253aa14a40e697eb2a68b7c602e8fafe56050d65928256"

      define_method(:install) do
        bin.install "meshbrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_linux_amd64.tar.gz"
      sha256 "f5e3c256996cc9724d59a78e5db98deefca451f9a50c215c1412808433702f43"
      define_method(:install) do
        bin.install "meshbrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_linux_arm64.tar.gz"
      sha256 "afd67ae80de2cf2d0575efc8475078d060f6606ab3abff9a1f273c64c1ad9d26"
      define_method(:install) do
        bin.install "meshbrow"
      end
    end
  end

  test do
    system "#{bin}/meshbrow", "version"
  end
end
