# typed: false
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser.
# Manual edits will be overwritten on next release.
class Meshbrow < Formula
  desc "CLI for the Meshbrow Managed Browser Fleet"
  homepage "https://meshbrow.dev"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/meshbrow-dev/meshbrow-backend/releases/download/v0.1.0/meshbrow_0.1.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    end

    on_arm do
      url "https://github.com/meshbrow-dev/meshbrow-backend/releases/download/v0.1.0/meshbrow_0.1.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/meshbrow-dev/meshbrow-backend/releases/download/v0.1.0/meshbrow_0.1.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    end

    on_arm do
      url "https://github.com/meshbrow-dev/meshbrow-backend/releases/download/v0.1.0/meshbrow_0.1.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    end
  end

  def install
    bin.install "meshbrow"
  end

  test do
    system "#{bin}/meshbrow", "version"
  end
end
