# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meshbrow < Formula
  desc "CLI for the Meshbrow Managed Browser Fleet"
  homepage "https://meshbrow.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_darwin_amd64.tar.gz"
      sha256 "6cf37fda285b060fa064b78f8c8ceaac10b16c74690e9229c85ea8beeef6141c"

      define_method(:install) do
        bin.install "meshbrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_darwin_arm64.tar.gz"
      sha256 "44145a5907e7f290a25e87d43222b5c68a127ac43c84c6ef0c08bba248bbf90d"

      define_method(:install) do
        bin.install "meshbrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_linux_amd64.tar.gz"
      sha256 "07737e3c0ea95937a168c624c5e883edfdf39fd9725719c4958e8e7a23b8926b"
      define_method(:install) do
        bin.install "meshbrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshbrow-dev/meshbrow-cli/releases/download/v0.1.0/meshbrow_0.1.0_linux_arm64.tar.gz"
      sha256 "2c5da83f390bb73cb6697a6356fdb54fc01c25462c1d486074ff0c5bb00fe4e1"
      define_method(:install) do
        bin.install "meshbrow"
      end
    end
  end

  test do
    system "#{bin}/meshbrow", "version"
  end
end
